
import java.sql.Statement;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chiiiii
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection con;
    Statement st;
    
    
    private static final String DBname = "foodtrackingsystem";
    private static final String DBDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DBUrl = "jdbc:mysql://localhost:3306/"+DBname;
    private static final String DBUsername = "root";
    private static final String DBPassword = "";
    
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DBDriver);
             con = DriverManager.getConnection(DBUrl, DBUsername, DBPassword);
             st = con.createStatement();
            
            if(con != null){
                System.out.println("Connection Succes");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        regTITLE = new javax.swing.JLabel();
        regEmail = new javax.swing.JLabel();
        regEntUSERNAME = new javax.swing.JTextField();
        regPass = new javax.swing.JLabel();
        regEntPASSWORD = new javax.swing.JTextField();
        regSubmitBtn = new javax.swing.JButton();
        accRegistered = new javax.swing.JLabel();
        txtLogBtn = new javax.swing.JButton();
        regEntCONFIRMPASSWORD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 246, 187));
        setPreferredSize(new java.awt.Dimension(738, 568));

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 246, 187));
        jPanel2.setPreferredSize(new java.awt.Dimension(494, 430));

        regTITLE.setBackground(new java.awt.Color(135, 169, 34));
        regTITLE.setFont(new java.awt.Font("Tw Cen MT", 0, 45)); // NOI18N
        regTITLE.setForeground(new java.awt.Color(17, 66, 50));
        regTITLE.setText("Register");

        regEmail.setBackground(new java.awt.Color(17, 66, 50));
        regEmail.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        regEmail.setForeground(new java.awt.Color(17, 66, 50));
        regEmail.setText("Enter Email");

        regEntUSERNAME.setToolTipText("");
        regEntUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEntUSERNAMEActionPerformed(evt);
            }
        });

        regPass.setBackground(new java.awt.Color(17, 66, 50));
        regPass.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        regPass.setForeground(new java.awt.Color(17, 66, 50));
        regPass.setText("Enter Password");

        regEntPASSWORD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                regEntPASSWORDComponentResized(evt);
            }
        });

        regSubmitBtn.setBackground(new java.awt.Color(17, 66, 50));
        regSubmitBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        regSubmitBtn.setForeground(new java.awt.Color(247, 246, 187));
        regSubmitBtn.setText("Submit");
        regSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSubmitBtnActionPerformed(evt);
            }
        });

        accRegistered.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        accRegistered.setText("Already have an account?");

        txtLogBtn.setBackground(new java.awt.Color(17, 66, 50));
        txtLogBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        txtLogBtn.setForeground(new java.awt.Color(247, 246, 187));
        txtLogBtn.setText("Log In");
        txtLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogBtnActionPerformed(evt);
            }
        });

        regEntCONFIRMPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEntCONFIRMPASSWORDActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(17, 66, 50));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 66, 50));
        jLabel1.setText("Confirm Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(regEntCONFIRMPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regEntPASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(regEmail)
                            .addComponent(regPass)
                            .addComponent(jLabel1)
                            .addComponent(regEntUSERNAME))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(regSubmitBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(regTITLE)))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(accRegistered)
                .addGap(18, 18, 18)
                .addComponent(txtLogBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(regTITLE)
                .addGap(18, 18, 18)
                .addComponent(regEmail)
                .addGap(18, 18, 18)
                .addComponent(regEntUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regPass)
                .addGap(18, 18, 18)
                .addComponent(regEntPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(regEntCONFIRMPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(regSubmitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accRegistered)
                    .addComponent(txtLogBtn))
                .addGap(73, 73, 73))
        );

        regEmail.getAccessibleContext().setAccessibleName("RegEmail");
        regEntUSERNAME.getAccessibleContext().setAccessibleName("EntEmail");
        regPass.getAccessibleContext().setAccessibleName("RegPASSWORD");
        regEntPASSWORD.getAccessibleContext().setAccessibleName("EntPass");

        jPanel3.setBackground(new java.awt.Color(17, 66, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEntUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEntUSERNAMEActionPerformed
                         // TODO add your handling code here:
    }//GEN-LAST:event_regEntUSERNAMEActionPerformed

    private void regSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSubmitBtnActionPerformed
            String regUsername, regPassword, confirmPassword;   
        if("".equals(regEntUSERNAME.getText())){
            JOptionPane.showMessageDialog(new JFrame(),"Required Username");            
        }
        else if (!regEntUSERNAME.getText().contains("@gmail.com")) {
            JOptionPane.showMessageDialog(new JFrame(), "Invalid Email. Please enter a valid Gmail address.");
        }
        else if("".equals(regEntPASSWORD.getText())){
            JOptionPane.showMessageDialog(new JFrame(),"Required Password");            
        }
        else if("".equals(regEntUSERNAME.getText())){
            JOptionPane.showMessageDialog(new JFrame(),"Required Password");            
        }
        else if("".equals(regEntCONFIRMPASSWORD.getText())){
        JOptionPane.showMessageDialog(new JFrame(),"Please confirm your password");            
        }      
        else {
        regUsername = regEntUSERNAME.getText();
        regPassword = regEntPASSWORD.getText();
        confirmPassword = regEntCONFIRMPASSWORD.getText();
        
        if (!regPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(new JFrame(), "Passwords do not match. Please re-enter your password.");
            regEntPASSWORD.setText("");
            regEntCONFIRMPASSWORD.setText("");
            return;
        }        
        
        else{
            regUsername = regEntUSERNAME.getText();
            regPassword = regEntPASSWORD.getText();
            
            String queryRegister = "INSERT INTO accdetails(accUsername, accPassword)"
                    + "VALUES ('" + regUsername + "', '" + regPassword + "')";
                    
        try {
            st.execute(queryRegister);
            JOptionPane.showMessageDialog(new JFrame(),"Register Successfully");
            Login login = new Login();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
        this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
       
        
        }
    }//GEN-LAST:event_regSubmitBtnActionPerformed

    private void regEntPASSWORDComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_regEntPASSWORDComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_regEntPASSWORDComponentResized

    private void regEntCONFIRMPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEntCONFIRMPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEntCONFIRMPASSWORDActionPerformed

    private void txtLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogBtnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
          
    }//GEN-LAST:event_txtLogBtnActionPerformed

    /**         
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accRegistered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel regEmail;
    private javax.swing.JTextField regEntCONFIRMPASSWORD;
    private javax.swing.JTextField regEntPASSWORD;
    private javax.swing.JTextField regEntUSERNAME;
    private javax.swing.JLabel regPass;
    private javax.swing.JButton regSubmitBtn;
    private javax.swing.JLabel regTITLE;
    private javax.swing.JButton txtLogBtn;
    // End of variables declaration//GEN-END:variables
}
